name: tests

on:
  push:
    branches:
      - master
      - dev
      - v1.x
  pull_request:
    branches:
      - master
      - dev
      - v1.x
  schedule:
    - cron: '0 0 20 * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - run: npm test --verbose
      - run: bash <(curl -s https://codecov.io/bash)
      - run: npm run build
